In [3]:
import numpy as np

In [6]:
x  = np.array(["V", 47, 57, 6.0])
print(x)
print(type(x))
print(x.dtype)

['V' '47' '57' '6.0']
<class 'numpy.ndarray'>
<U32


In [8]:
v1 = np.array([[20, 30], [40, 50]])
print(v1)
print(type(v1))
print(v1.shape)

[[20 30]
 [40 50]]
<class 'numpy.ndarray'>
(2, 2)


In [14]:
#Reshaping an array
a=np.array([10,20,30,40])
b=a.reshape(2,2)
print(b)
print(b.shape)

[[10 20]
 [30 40]]
(2, 2)


In [15]:
#create an array with arange function
c = np.arange(2, 30)
print(c)
type(c)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29]


numpy.ndarray

In [18]:
d = np.array([1.456, 2.5678, 3.6789])
d

array([1.456 , 2.5678, 3.6789])

In [19]:
print(np.sqrt(d))

[1.20664825 1.60243565 1.91804588]


In [20]:
print(np.around(np.sqrt(d),2))

[1.21 1.6  1.92]


In [23]:
a = np.array([[2,3,4,5],[6,7,8, np.NAN]])
print(a)
a.dtype

[[ 2.  3.  4.  5.]
 [ 6.  7.  8. nan]]


dtype('float64')

In [24]:
a_copy1 = a.astype(str)
print(a_copy1)

[['2.0' '3.0' '4.0' '5.0']
 ['6.0' '7.0' '8.0' 'nan']]


In [26]:
#Mathemaetical operations on row and col
a2 = np.array([[2,3,4],[4,5,6],[6,7,8]])
a2

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [27]:
print(a2.sum(axis = 1))
print(a2.sum(axis=0))

[ 9 15 21]
[12 15 18]


In [29]:
#matrix
a3 = np.array([[3,4,5],[4,5,6],[6,7,8]])
a3
np.fill_diagonal(a3,0)
print(a3)

[[0 4 5]
 [4 0 6]
 [6 7 0]]


In [31]:
#defien two matrices
A = np.array([[1,2],[2,3]])
B = np.array([[4,5],[5,6]])
C = np.matmul(A,B)
C

array([[14, 17],
       [23, 28]])

In [32]:
#transpose of the matrix
print(A.T)
print(B.T)

[[1 2]
 [2 3]]
[[4 5]
 [5 6]]


In [33]:
#accessing the array elements
a = np.array([[2,3,4],[4,5,6],[5,6,7],[6,7,8]])
a

array([[2, 3, 4],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [34]:
#slicing of array
a[:,1:]

array([[3, 4],
       [5, 6],
       [6, 7],
       [7, 8]])

In [44]:
a[1:3,0:2]

array([[4, 5],
       [5, 6]])